#!/bin/bash

if [ "$KOREAPI_COMMAND" == "PUSH_TO_S3" ]; then
  end=`date -d "$DOMAIN_REPORT_ENDING_DATE" +'%Y-%m-%d'`
  start=`date -d "$end - $DOMAIN_REPORT_INTERVAL_BACK" +'%Y-%m-%d'`
  if [ -z ${KOREAPI_HOST+x} ]; then
    KOREAPI_HOST='koreapi'
  fi

  if [ -z ${KOREAPI_PORT+x} ]; then
    KOREAPI_PORT='4567'
  fi

  curl -s -S "http://${KOREAPI_HOST}:${KOREAPI_PORT}/scriptlet/domain_report?&start=${start}&end=${end}&push_to_s3=true&period=$DOMAIN_REPORT_PERIOD"
else
  set -e

  # If AWS Credentials were configured then source the Environment variables.
  [ -f "/dev/shm/${AWS_CONFIG}" ] && source "/dev/shm/${AWS_CONFIG}"

  /bin/env_parse ${CONFIG_DIR}/${KOREAPI_CONFIG}.j2

  cd ${APP_DIR}


  # Using exec to replace the current bash script running with PID1 with Unicorn
  # This allows docker to send signals to unicorn, allowing for graceful shutdown
  exec su socrata -c "bundle exec ruby koreapi.rb"
fi
